name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - ipycanvas
  - numpy
  - matplotlib
  - seaborn
  - plotnine
  - pandas
  - statsmodels
  - scikit-learn
  - scipy
  - sqlite
  - altair
  - ipympl
  - ipyleaflet
  - ipydatagrid
  - ipycanvas
  - vega_datasets
  - plotly
  - bqplot
  - black
  - pyviz_comms
  - openpyxl
  - python-tzdata
  - httpx
  - xarray
  - pip:
    - ./urllib3-2.1.0-py3-none-any.whl
    - ./frozenlist-1.4.0-py3-none-any.whl
    - ./multidict-4.7.6-py3-none-any.whl
    - ./aiohttp-3.9.1-py3-none-any.whl
    - ./xeus_python_shell-0.6.1-py3-none-any.whl
  - openai
  - langchain
