name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - ipycanvas
  - numpy==1.26.1
  - matplotlib
  - seaborn
  - plotnine
  - pandas==2.1.2
  - statsmodels
  - scikit-learn
  - scipy
  - sqlite
  - altair
  - ipympl
  - ipyleaflet
  - ipydatagrid
  - ipycanvas
  - vega_datasets
  - plotly
  - bqplot
  - black
  - pyviz_comms
  - openpyxl
  - python-tzdata
  - httpx
  - xarray
